version: '3.7'
services:
  mysql:
      image: mysql:latest
      container_name: shop-dev
      restart: always
      hostname: mysql02
      ports:
        - "33062:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=dev
        - MYSQL_DATABASE=foolball_dev
        - MYSQL_USER=dev
        - MYSQL_PASSWORD=dev
      volumes:
        - ./db/dbdata:/var/lib/mysql
        - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      networks:
        - default
