version: '3.8'
services:
  football-mysql-db:
    image: mysql:latest
    container_name: football
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
    command: --init-file /data/application/init.sql
    volumes:
      - ../db/dbdata:/var/lib/mysql
      - ../db/my.cnf/config.cnf:/etc/mysql/conf.d/my.cnf
      - ../migrate/zujstorage.sql:/data/application/init.sql
    networks:
      - default

volumes:
  db: